#----------------------------------------------------------------------------#
# Fyyur -- application entry point.
#
# The starter kept models, forms, controllers and configuration in this one
# file.  They now live where they belong:
#
#   config.py       environment-driven settings (including the database URL)
#   extensions.py   the SQLAlchemy / Migrate / Moment singletons
#   models.py       the schema and every query that reads or writes it
#   forms.py        Flask-WTF forms and their validation rules
#   filters.py      Jinja filters
#   controllers/    one blueprint per resource
#   seed.py         demo data, loadable with `flask seed`
#
# What is left here is the factory that wires those parts together, the CLI
# commands, and logging.
#----------------------------------------------------------------------------#

import logging
import os
from logging import FileHandler, Formatter

import click
from flask import Flask

from config import config_by_name
from controllers import register_blueprints
from extensions import csrf, db, migrate, moment
from filters import register_filters

# Importing the models has a side effect the migrations depend on: it registers
# every table with `db.metadata`, which is what `flask db migrate` compares
# against the live database.
import models  # noqa: F401  (imported for its side effect)


def create_app(config_name=None):
    """Build and configure an application instance.

    A factory rather than a module-level app so the test suite can create an
    isolated instance pointed at the test database, without the two sharing
    configuration or connection pools.
    """
    app = Flask(__name__)
    app.config.from_object(
        config_by_name[config_name or os.environ.get('FYYUR_CONFIG', 'default')]
    )

    db.init_app(app)
    # `render_as_batch` keeps autogenerated migrations working if this schema is
    # ever pointed at SQLite, which cannot ALTER a column in place.
    migrate.init_app(app, db, render_as_batch=False)
    moment.init_app(app)
    csrf.init_app(app)

    register_filters(app)
    register_blueprints(app)
    register_cli(app)
    configure_logging(app)

    @app.context_processor
    def inject_now():
        """`now` in every template, for "is this window in the past?" checks."""
        from models import utcnow

        return {'now': utcnow()}

    return app


#----------------------------------------------------------------------------#
# CLI
#----------------------------------------------------------------------------#

def register_cli(app):
    """Project commands, available as `flask <name>`."""

    @app.cli.command('seed')
    @click.option('--reset/--no-reset', default=True,
                  help='Delete existing rows first (default: reset).')
    def seed_command(reset):
        """Load the demo catalogue of venues, artists, shows and albums."""
        from seed import seed_all

        summary = seed_all(reset=reset)
        for table, count in summary.items():
            click.echo('  {:<14} {}'.format(table, count))
        click.echo('Seeded.')

    @app.cli.command('seed-genres')
    def seed_genres_command():
        """Populate the Genre lookup table without touching anything else."""
        from seed import seed_genres

        click.echo('{} genres present.'.format(seed_genres()))

    @app.cli.command('sql-preview')
    @click.argument('name', required=False)
    def sql_preview_command(name):
        """Print the SQL that each ORM query helper compiles to."""
        from sql_preview import print_previews

        print_previews(name)


#----------------------------------------------------------------------------#
# Logging
#----------------------------------------------------------------------------#

def configure_logging(app):
    if app.debug or app.testing:
        return

    file_handler = FileHandler('error.log')
    file_handler.setFormatter(Formatter(
        '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
    ))
    file_handler.setLevel(logging.INFO)
    app.logger.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)
    app.logger.info('errors')


# `flask` and `python app.py` both need a module-level application object.
app = create_app()


#----------------------------------------------------------------------------#
# Launch.
#----------------------------------------------------------------------------#

if __name__ == '__main__':
    # Default port 5000; override with PORT=3000 to match the Udacity
    # workspace, which proxies that port.
    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))
