"""fyyur schema: venues, artists, shows, genres, availability, discography

Revision ID: 60bf9711705f
Revises: 
Create Date: 2026-09-20 18:12:18.006203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bf9711705f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seeking_venue', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')", name='ck_artist_state'),
    sa.CheckConstraint('NOT seeking_venue OR seeking_description IS NOT NULL', name='ck_artist_seeking_description'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_artist_name_present'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city', 'state', name='uq_artist_name_city')
    )
    op.create_index(op.f('ix_Artist_created_at'), 'Artist', ['created_at'], unique=False)
    op.create_index('ix_artist_city_state', 'Artist', ['city', 'state'], unique=False)
    op.create_index('ix_artist_name_lower', 'Artist', [sa.literal_column('lower(name)')], unique=False)
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.CheckConstraint("name IN ('Alternative', 'Blues', 'Classical', 'Country', 'Electronic', 'Folk', 'Funk', 'Hip-Hop', 'Heavy Metal', 'Instrumental', 'Jazz', 'Musical Theatre', 'Pop', 'Punk', 'R&B', 'Reggae', 'Rock n Roll', 'Soul', 'Swing', 'Other')", name='ck_genre_name_allowed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('seeking_talent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY')", name='ck_venue_state'),
    sa.CheckConstraint('NOT seeking_talent OR seeking_description IS NOT NULL', name='ck_venue_seeking_description'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_venue_name_present'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', 'city', 'state', name='uq_venue_name_address')
    )
    op.create_index(op.f('ix_Venue_created_at'), 'Venue', ['created_at'], unique=False)
    op.create_index('ix_venue_city_state', 'Venue', ['city', 'state'], unique=False)
    op.create_index('ix_venue_name_lower', 'Venue', [sa.literal_column('lower(name)')], unique=False)
    op.create_table('Album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('release_year IS NULL OR (release_year BETWEEN 1877 AND 2100)', name='ck_album_release_year'),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'name', name='uq_album_artist_name')
    )
    op.create_index(op.f('ix_Album_artist_id'), 'Album', ['artist_id'], unique=False)
    op.create_index(op.f('ix_Album_created_at'), 'Album', ['created_at'], unique=False)
    op.create_table('ArtistGenre',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('Availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_order'),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'start_time', 'end_time', name='uq_availability_window')
    )
    op.create_index(op.f('ix_Availability_artist_id'), 'Availability', ['artist_id'], unique=False)
    op.create_index(op.f('ix_Availability_created_at'), 'Availability', ['created_at'], unique=False)
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'start_time', name='uq_show_artist_start_time')
    )
    op.create_index(op.f('ix_Show_artist_id'), 'Show', ['artist_id'], unique=False)
    op.create_index(op.f('ix_Show_created_at'), 'Show', ['created_at'], unique=False)
    op.create_index(op.f('ix_Show_start_time'), 'Show', ['start_time'], unique=False)
    op.create_index(op.f('ix_Show_venue_id'), 'Show', ['venue_id'], unique=False)
    op.create_table('VenueGenre',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.create_table('Song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds > 0', name='ck_song_duration'),
    sa.CheckConstraint('track_number IS NULL OR track_number > 0', name='ck_song_track_number'),
    sa.ForeignKeyConstraint(['album_id'], ['Album.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'title', name='uq_song_album_title'),
    sa.UniqueConstraint('album_id', 'track_number', name='uq_song_album_track')
    )
    op.create_index(op.f('ix_Song_album_id'), 'Song', ['album_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Song_album_id'), table_name='Song')
    op.drop_table('Song')
    op.drop_table('VenueGenre')
    op.drop_index(op.f('ix_Show_venue_id'), table_name='Show')
    op.drop_index(op.f('ix_Show_start_time'), table_name='Show')
    op.drop_index(op.f('ix_Show_created_at'), table_name='Show')
    op.drop_index(op.f('ix_Show_artist_id'), table_name='Show')
    op.drop_table('Show')
    op.drop_index(op.f('ix_Availability_created_at'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_artist_id'), table_name='Availability')
    op.drop_table('Availability')
    op.drop_table('ArtistGenre')
    op.drop_index(op.f('ix_Album_created_at'), table_name='Album')
    op.drop_index(op.f('ix_Album_artist_id'), table_name='Album')
    op.drop_table('Album')
    op.drop_index('ix_venue_name_lower', table_name='Venue')
    op.drop_index('ix_venue_city_state', table_name='Venue')
    op.drop_index(op.f('ix_Venue_created_at'), table_name='Venue')
    op.drop_table('Venue')
    op.drop_table('Genre')
    op.drop_index('ix_artist_name_lower', table_name='Artist')
    op.drop_index('ix_artist_city_state', table_name='Artist')
    op.drop_index(op.f('ix_Artist_created_at'), table_name='Artist')
    op.drop_table('Artist')
    # ### end Alembic commands ###
